site_name: CHBH-on-BEAR
site_url: https://ajquinn.github.io/chbh-on-bear/

repo_name: CHBH-on-BEAR
repo_url: https://github.com/AJQuinn/chbh-on-bear
edit_uri: blob/main/docs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

theme:
  name: material
  features:
    - content.code.copy
  logo: images/CHBH_logo.jpg
  favicon: images/CHBH_logo.jpg

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - EEG:
    - FieldTrip: eeg/fieldtrip.md
  - MEG:
    - MNE: meg/mne.md
  - MRI:
    - fMRIPrep: mri/fmriprep.md
    - FreeSurfer: mri/freesurfer.md
    - FSL: mri/fsl.md
    - SPM: mri/spm.md
  - Software:
    - Conda: software/conda.md
    - Containers: software/containers.md
    - MATLAB: software/matlab.md
    - Python: software/python.md
    - R: software/R.md
  - FAQs: faqs.md
