site_name: CHBH-on-BEAR
site_url: https://ajquinn.github.io/chbh-on-bear/

repo_name: CHBH-on-BEAR
repo_url: https://github.com/AJQuinn/chbh-on-bear
edit_uri: blob/main/docs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html

theme:
  name: material
  features:
    - content.code.copy
  logo: images/CHBH_logo.jpg
  favicon: images/CHBH_logo.jpg

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - EEG:
    - eeg/index.md
    - Hardware:
      - The EEG System: eeg/hardware/eeg.md
    - Analysis Tools:
      - FieldTrip: eeg/analysis/fieldtrip.md
    - Software:
      - PsychoPy: eeg/software/psychopy.md
  - MEG:
    - meg/index.md
    - Hardware:
      - The MEG System: meg/hardware/meg.md
    - Analysis Tools:
      - MNE-Python: meg/analysis/mne.md
    - Software:
      - PsychoPy: meg/software/eprime.md
  - MRI:
    - mri/index.md
    - Hardware:
      - The MRI Scanner: mri/hardware/scanner.md
      - Stimulus Equipment: mri/hardware/stimulus_equipment.md
      - Troubleshooting: mri/hardware/troubleshooting.md
    - Analysis Tools:
      - fMRIPrep: mri/analysis/fmriprep.md
      - FreeSurfer: mri/analysis/freesurfer.md
      - FSL: mri/analysis/fsl.md
      - SPM: mri/analysis/spm.md
    - Software:
      - PsychoPy: mri/software/psychopy.md
      - PsychToolbox: mri/software/psychtoolbox.md
  - Brain Stimulation:
    - TMS: brainstim/tms.md
  - Software on BEAR:
    - software/index.md
    - Conda: software/conda.md
    - Containers: software/containers.md
    - MATLAB: software/matlab.md
    - Python: software/python.md
    - R: software/R.md
  - Making a contribution : making_a_contribution.md
  - FAQs: faqs.md
